domainLengthX: 20
domainLengthY: 20
gridSizeX: 20
gridSizeY: 20
gridSpacingX: 1
gridSpacingY: 1
timeStep: 1e-08
timeSteps: 100000000
outputInterval: 1000000
epsilon: 0.5
boundaryType: Periodic
simulationTag: 2d_from_random
