domainLength: 80
gridSize: 100
gridSpacing: 0.8
timeStep: 1e-06
timeSteps: 2000000
outputInterval: 20000
r: -0.4
Gamma: 1
Gamma_S: 1
rho_0: 0.001
a_0: 5.71429
boundaryType: Periodic
useExternalForce: 1
forceAmplitude: 4
forceMode: 1
forceOmega: 20
simulationTag: sHPFC_periodic_forced_6
