domainLengthX: 20
domainLengthY: 20
gridSizeX: 20
gridSizeY: 20
gridSpacingX: 1
gridSpacingY: 1
timeStep: 0.0001
timeSteps: 1000000
outputInterval: 10000
epsilon: 0.4
boundaryType: Periodic
simulationTag: 2d_random_-0.3avg
