domainLength: 80
gridSize: 100
gridSpacing: 0.8
timeStep: 1e-06
timeSteps: 5000000
outputInterval: 50000
r: -0.4
Gamma: 1
Gamma_S: 1
rho_0: 0.001
a_0: 5.71429
boundaryType: Periodic
simulationTag: sHPFC_velocity_2
