domainLength: 80
gridSize: 101
gridSpacing: 0.8
timeStep: 1e-06
timeSteps: 20000000
outputInterval: 200000
r: -0.4
Gamma: 1
Gamma_S: 1
rho_0: 0.001
a_0: 5.71429
scalarBoundaryType: NeumannZero
velocityBoundaryType: DirichletZero
simulationTag: sHPFC_spring_in_jar_06
gravityX: -4
